### PR TITLE
Added CRAN version and monthly download badges.

### LINKED ISSUE #13: Update README to include badges
Add the following badges:

- [x] Monthly downloads
- [x] CRAN version

### PR DESCRIPTION
**Pull request by rachmaninoffpk**
This closes #13 .

### CODE REVIEW

**Comment by rachmaninoffpk** [comment]
It looks like the new styling for the vignettes has pushed the package to around 9 mb in size, exceeding the 5 mb limit. It may be better to use the original vignettes for now and add the new versions to a directory that would be used by Pkgdown.

**Comment by madison-feshuk** [comment]
@rachmaninoffpk can you run the devtools check again? Removed formatting in data domains vignettes, but kept rmdsformat of main vignette

**Comment by rachmaninoffpk** [comment]
The package is now 5.2 MB of which 4.7 MB are from the docs subdirectory. It looks like the Introduction accounts for 2.39 MB while the others are much smaller. A slight reduction in the Introduction vignette will probably be enough to move it back into CRAN compliance.

**Comment by rachmaninoffpk** [comment]
Image size has been reduced and the built package is no longer too large for CRAN.

**Review by madison-feshuk — APPROVED** [review]
Approving, but we may want to consider updating format of the data domain vignettes to rmdsformat or combining in the future (will be under a separate ticket)

**Pull request merged**
